accounts/urls.py
from django.urls import path ,include
from . import views

app_name = 'accounts'

urlpatterns = [

    path('signup', views.signup,name='signup'),
    path('profile/', views.profile,name='profile'),
    path('profile/edit', views.profile_edit,name='profile_edit'), 
    

]

event/urls.py
from django.urls import path ,include
from . import views
from . import api

app_name = 'event'

urlpatterns = [

    path('', views.event_weekly,name='event_weekly'),
    path('events_list', views.events_list,name='events_list'),
    path('add_event', views.add_event,name='add_event'),
    path('<str:eve_slug>', views.event_detail,name='event_detail'),
    path('api/event', api.EventListApi.as_view() ,name='event_list_api'),
    path('api/event/<int:id>', api.Event_DetailApi.as_view() ,name='event_detail_api'),

]

project/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
    # path('event/', include('event.urls',namespace='event')),
    path('', include('event.urls')),
    path('contact-us/', include('contact.urls',namespace='contact')),
    path('api-auth/', include('rest_framework.urls')),
    # path('venue/', include('venue.urls',namespace='venue')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from datetime import datetime
from django.db.models.signals import post_save
from django.dispatch import receiver


def image_upload(instance, filename):
    now = datetime.now()
    timestamp = now.strftime('%Y%m%d%H%M%S')
    folder_path = f'user/{instance.user.id}'
    image_path = f'{folder_path}/{timestamp}.png'
    return image_path


#user models
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    image = models.ImageField( upload_to=image_upload, null=True , blank=True)
    phone_number = models.CharField(("Phone Number"), max_length=20)
    city = models.ForeignKey('City', on_delete=models.CASCADE, null=True , blank=True)
    is_venue = models.BooleanField(default=False)
    def __str__(self):
        return f'{self.user.username}'
    
@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)




class City(models.Model):
    name = models.CharField(max_length=50 )
    def __str__(self):
        return f'{self.name} '
    

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile


class SingUpForm (UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

class UserUpdateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']

class ProfileUpdateForm (forms.ModelForm):
    
    class Meta:
        model = Profile
        fields = ['image','phone_number','city']
        widgets = {
            'city': forms.Select(attrs={'style': 'height: auto;'}),
        }

accounts/views.py
from django.shortcuts import redirect, render
from django.urls import reverse
from .forms import SingUpForm , UserUpdateForm , ProfileUpdateForm 
from django.contrib.auth import authenticate
from django.contrib.auth import login
from .models import Profile
from django.contrib.auth.decorators import login_required

# Create your views here.
def signup (request):
    if request.method == 'POST':
        form = SingUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            password = form.cleaned_data.get('password1')
            user = authenticate(username=username,password=password)
            login(request,user)
            return redirect('/accounts/profile')
    else:
        form = SingUpForm()
    return render(request,'registration/signup.html',{'form':form})
@login_required
def profile (request):
    profile = Profile.objects.get(user=request.user)
    return render(request,'accounts/profile.html',{'profile':profile})
@login_required
def profile_edit (request):
    user_profile = Profile.objects.get(user=request.user)
    if request.method == 'POST':
        userform = UserUpdateForm(request.POST,instance=request.user)
        profileform   = ProfileUpdateForm (request.POST,request.FILES,instance=user_profile)
        context = {
            'userform':userform,
            'profileform':profileform  ,
        }
        if userform.is_valid() and profileform.is_valid():
            userform.save()
            myprofile = profileform.save(commit=False)
            myprofile.user = request.user
            myprofile.save()
            return redirect(reverse("accounts:profile"))

    else:
        userform = UserUpdateForm(instance=request.user)
        profileform   = ProfileUpdateForm (instance=user_profile)
        context = {
            'userform':userform,
            'profileform':profileform  ,
        }
    return render(request,'accounts/profile_edit.html',context)

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}



{% block body %}
    
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>{{event_detail}}</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">

                <div class="col-lg-10 mx-auto">
                    <div class="job_sumary">
                        <div class="summery_header">
                            <h3>Profile Summery</h3>
                        </div>
                        <div class="job_content">
                            <ul>
                                <li>Name: <span>{{profile}}</span></li>
                                <li>Emiel: <span>{{profile.user.email}}</span></li>
                                <li>Phonr: <span>{{profile.phone_number}}</span></li>
                                <li>Location: <span> {{profile.city}}</span></li>
                            </ul>

                        </div>
                        <div class ="p-5">
                            <a class = "boxed-btn3 w-100" href="{% url 'accounts:profile_edit' %}">Edit Profile</a>

                        </div>
                    </div>


                </div>
            </div>
        </div>
    </div>
{% endblock body%}

accounts/templates/accounts/profile_edit.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}



{% block body %}
    
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">

        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 mx-auto">

                    <div class="apply_job_form white-bg">
                        <h4>Edit Profile</h4>
                        <form  method="POST" enctype="multipart/form-data">
                            
                            {% csrf_token %}
                            {% bootstrap_form userform %}
                            {% bootstrap_form profileform %}
           
                            <button class="boxed-btn3 w-100" type="submit" style="margin-top: 15px;">Save</button>

                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>
{% endblock body%}