event/urls.py
from django.urls import path ,include
from . import views
from . import api

app_name = 'event'

urlpatterns = [

    path('', views.event_weekly,name='event_weekly'),
    path('events_list', views.events_list,name='events_list'),
    path('add_event', views.add_event,name='add_event'),
    path('<str:eve_slug>', views.event_detail,name='event_detail'),
    path('api/event', api.EventListApi.as_view() ,name='event_list_api'),
    path('api/event/<int:id>', api.Event_DetailApi.as_view() ,name='event_detail_api'),

]

project/urls.py
from django.contrib import admin
from django.urls import path ,include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
    # path('event/', include('event.urls',namespace='event')),
    path('', include('event.urls')),
    path('contact-us/', include('contact.urls',namespace='contact')),
    path('api-auth/', include('rest_framework.urls')),
    # path('venue/', include('venue.urls',namespace='venue')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

venue/urls.py
from django.urls import path 
from . import views

app_name = 'venue'

urlpatterns = [


    path('<str:ve_slug>', views.venue_detail,name='venue_detail'),
]

venue/models.py
import os
from django.db import models
from django.utils.translation import gettext as _
from django.utils.text import slugify
from datetime import datetime
from unidecode import unidecode
from multiselectfield import MultiSelectField




STARS = [
        (0, '0'),
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
    ]


def image_upload(instance, image):
    now = datetime.now()
    timestamp = now.strftime('%Y%m%d%H%M%S')
    instance.save()
    instance.refresh_from_db()
    folder_path = f'Venue/{instance.id}'
    os.makedirs(folder_path, exist_ok=True)
    image_path = f'{folder_path}/{timestamp}.png'
    return image_path

class VenueCatagory(models.Model):
    cat_ve_name = models.CharField(_("Venue Catagory"), max_length=50)
    class Meta:
        verbose_name = _("Catagory")
        verbose_name_plural = _("Categories")
    def __str__(self):
        return self.cat_ve_name

class Venue(models.Model):
    ve_name = models.CharField('Venue Name', max_length=120)
    ve_description = models.TextField(_("Venue Description"))
    ve_address = models.CharField(_("Venue Address"),max_length=300)
    ve_phone = models.CharField('Contact Phone', max_length=20, )
    ve_email_address = models.EmailField('Email Address', null=True, blank=True )
    ve_catagory = models.ForeignKey( VenueCatagory,verbose_name=_("Catagory"), on_delete=models.CASCADE)
    ve_zip_code = models.CharField('Zip/Post Code', max_length=12, null=True ,blank=True )
    ve_web = models.URLField('Website Address', null=True, blank=True )
    ve_slug = models.SlugField(null=True,blank=True)
    ve_image = models.ImageField(_("Venue Image"), upload_to=image_upload)
    ve_star = models.IntegerField(("Venue Star"),default=0,choices=STARS)
        
    def save(self,*args,**kwargs):
        latin_name = unidecode(self.ve_name)
        self.ve_slug = slugify(latin_name)
        super(Venue , self).save(*args,**kwargs)
    def __str__(self):
        return str(self.ve_name)

venue/forms.py
from django import forms
from .models import Venue


class VenueForm(forms.ModelForm):
    class Meta:
        model = Venue
        fields = '__all__'
        exclude = ('ve_slug','ve_image')
        

venue/views.py
from django.shortcuts import render
from .models import Venue

def venue_detail(request,ve_slug):
    venue_detail = Venue.objects.get(ve_slug=ve_slug)
    context = {'venue_detail':venue_detail}
    return render(request,'venue/venue_detail.html',context)

venue/templates/venue/add_venue.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}

{% block body %}
    
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_t   ext">
                        <h3>Add New Event</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 mx-auto">

                    <div class="apply_job_form white-bg">
                        <h4>Post New Event</h4>
                        <form  method="POST" enctype="multipart/form-data">       

                            {% csrf_token %}
                            <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
                            {{ form.media }}
                            {% bootstrap_form form %}
                            
                            <button class="boxed-btn3 w-100 mt-2" type="submit">Share Event</button>

                        </form>
                    </div>
                </div>

            </div>
        </div>
    </div>
{% endblock body%}

venue/templates/venue/venue_detail.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}



{% block body %}
    
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>{{event_detail}}</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 mx-auto">
                    <div class="job_details_header">
                        <div class="single_jobs white-bg d-flex justify-content-between">
                            <div class="jobs_left d-flex align-items-center">
                                <div class="thumb p-0" style="border-radius: 10px; overflow: hidden;">
                                    <img src="{{event_detail.eve_image.url}}" alt="" style="width: 100%; height: 100%; object-fit: cover;">
                                </div>
                                <div class="jobs_conetent">
                                    <a href="#"><h4>{{event_detail}}</h4></a>
                                    <div class="links_locat d-flex align-items-center">
                                        <div class="location">
                                            <p> <i class="fa fa-map-marker"></i>{{event_detail.eve_venue}}</p>
                                        </div>
                                        <div class="location">
                                            <p> <i class="fa fa-clock-o"></i> {{event_detail.eve_date_start}}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="jobs_right">
                                <div class="reservation_now">
                                    <a class="heart_mark" href="#"> <i class="ti-heart"></i> </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="descript_wrap white-bg">
                        <div class="single_wrap">
                            <h4>Event description</h4>
                            <p style="font-size: 20px;">{{event_detail.eve_description}}</p>
                        </div>
                    </div>
                    <div class="apply_job_form white-bg">
                        <h4>Reservation for the Event</h4>
                        <form action="#" method="POST">
                            
                            {% csrf_token %}

                            {% bootstrap_form form %}
                        
                            <button class="boxed-btn3 w-100" type="submit">Reservation Now</button>
  
                        </form>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="job_sumary">
                        <div class="summery_header">
                            <h3>Event Summery</h3>
                        </div>
                        <div class="job_content">
                            <ul>
                                <li>Published on: <span>{{event_detail.eve_published_at}}</span></li>
                                <li>style: <span>{{event_detail.eve_type}}</span></li>
                                <li>Date: <span>{{event_detail.eve_datetime_start}}</span></li>
                                <li>Time: <span>{{event_detail.eve_time_start}}</span></li>
                                <li>Location: <span> {{event_detail.eve_description}}</span></li>
                            </ul>
                        </div>
                    </div>
                    <div class="share_wrap d-flex">
                        <span>Share at:</span>
                        <ul>
                            <li><a href="#"> <i class="fa fa-facebook"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-google-plus"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-twitter"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-envelope"></i></a> </li>
                        </ul>
                    </div>
                    <div class="job_location_wrap">
                        <div class="job_lok_inner">
                            <div id="map" style="height: 200px;"></div>
                            <script>
                              function initMap() {
                                var uluru = {lat: -25.363, lng: 131.044};
                                var grayStyles = [
                                  {
                                    featureType: "all",
                                    stylers: [
                                      { saturation: -90 },
                                      { lightness: 50 }
                                    ]
                                  },
                                  {elementType: 'labels.text.fill', stylers: [{color: '#ccdee9'}]}
                                ];
                                var map = new google.maps.Map(document.getElementById('map'), {
                                  center: {lat: -31.197, lng: 150.744},
                                  zoom: 9,
                                  styles: grayStyles,
                                  scrollwheel:  false
                                });
                              }
                              
                            </script>
                            <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDpfS1oRGreGSBU5HHjMmQ3o5NLw7VdJ6I&callback=initMap"></script>
                            
                          </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock body%}

venue/templates/venue/venue_list.html
{% extends 'base.html' %}
{% load django_bootstrap5 %}
{% block body %}
    

    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>{{events_list.count}}+ events_list</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <!-- job_listing_area_start  -->
    <div class="job_listing_area plus_padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="job_filter white-bg">
                        <div class="form_inner white-bg">
                            <h3>Filter</h3>
                            <form method="GET">
                                {% bootstrap_form my_filter.form %}
                        
                                <input type="submit" value="search" class="boxed-btn3 w-100 mt-2">
                            </form>
                        </div>

                      
                    </div>
                </div>
                <div class="col-lg-9">
                    <div class="recent_joblist_wrap">
                        <div class="recent_joblist white-bg ">
                            <div class="row align-items-center">
                                <div class="col-md-6">
                                    <h4>Job Listing</h4>
                                </div>
                                <div class="col-md-6">
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="job_lists m-0">
                        <div class="row">
                            {% for event in events_list %}
                            <div class="col-lg-12 col-md-12">
                                <div class="single_jobs white-bg d-flex justify-content-between">
                                    <div class="jobs_left d-flex align-items-center">
                                        <div class="thumb p-0" style="border-radius: 10px; overflow: hidden;">
                                            <img src="{{event.eve_image.url}}" alt="" style="width: 100%; height: 100%; object-fit: cover;">
                                        </div>
                                        <div class="jobs_conetent">
                                            <a href="{% url 'event:event_detail' event.eve_slug %}"><h4>{{event}}</h4></a>
                                            <div class="links_locat d-flex align-items-center">
                                                <div class="location">
                                                    <p> <i class="fa fa-map-marker"></i>{{event.eve_venue}}</p>
                                                </div>
                                                <div class="location">
                                                    <p> <i class="fa fa-clock-o"></i>{{event.eve_date_start}}</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="jobs_right">
                                        <div class="apply_now">
                                            <a class="heart_mark" href="#"> <i class="fa fa-heart"></i> </a>
                                            <a href="{% url 'event:event_detail' event.eve_slug %}" class="boxed-btn3">Apply Now</a>
                                        </div>
                                        <div class="date">
                                            <p>welcome</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}

                        </div>
                        {% if events_list.has_other_pages %}
                        <div class="row">
                            <div class="col-lg-12">
                                <div class="pagination_wrap">
                                    <ul>
                                        {% if events_list.has_previous  %}
                                            <li><a href="?page={{events_list.previous_page_number}}"> <i class="ti-angle-left"></i> </a></li>
                                        {% endif %}

                                        {% for i in events_list.paginator.page_range  %}
                                            <li><a href="?page={{i}}"><span>{{i}}</span></a></li>
                                        {% endfor %}

                                        {% if events_list.has_next  %}
                                        <li><a href="?page={{events_list.next_page_number}}"> <i class="ti-angle-right"></i> </a></li>
                                        {% endif %}
                                    </ul>
                                </div>
                            </div>
                        </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- job_listing_area_end  -->

{% endblock body%}